name = "hashi"
compatibility_date = "2025-08-03"
main = "./src/index.tsx"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "hashi-db"
